/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Home",
  "tagline": "Secure, HIPAA-compliant healthcare information management with MongoDB Queryable Encryption",
  "url": "https://docs.securehealth.dev",
  "baseUrl": "/es/",
  "projectName": "mrlynn.github.io",
  "organizationName": "mrlynn",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.svg",
  "staticDirectories": [
    "static"
  ],
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "es"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "customFields": {
    "startButtonTitle": "Start Demo",
    "featureList": [
      {
        "title": "Security by Design",
        "illustration": "img/coding.png",
        "description": "\n        Built with HIPAA compliance and MongoDB Queryable Encryption from the ground up.\n    "
      },
      {
        "title": "Interactive Demo",
        "illustration": "img/highfive.png",
        "description": "\n        Experience encrypted medical records management with our live demo.\n    "
      },
      {
        "title": "Role-Based Access",
        "illustration": "img/writing.png",
        "description": "\n        Granular permissions for doctors, nurses, and receptionists.\n    "
      },
      {
        "title": "Patient Portal",
        "illustration": "img/rocket.png",
        "description": "\n        Secure patient access to medical records and communication tools.\n    "
      }
    ],
    "utmParams": "utm_campaign=devrel&utm_source=workshop&utm_medium=cta&utm_content=securehealth_docs&utm_term=mrlynn"
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/michael.lynn/code/symfony/securedev-docs/sidebars.js"
        },
        "theme": {
          "customCss": "/Users/michael.lynn/code/symfony/securedev-docs/src/css/custom.css"
        },
        "gtag": {
          "trackingID": "G-ZJ28V71VTQ",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "plugins": [
    [
      "/Users/michael.lynn/code/symfony/securedev-docs/node_modules/docusaurus-lunr-search/src/index.js",
      {
        "languages": [
          "es",
          "en"
        ]
      }
    ]
  ],
  "themeConfig": {
    "docs": {
      "sidebar": {
        "autoCollapseCategories": true,
        "hideable": true
      },
      "versionPersistence": "localStorage"
    },
    "announcementBar": {
      "id": "live_demo",
      "content": "🚀 <strong>Live Demo Available!</strong> Experience SecureHealth in action at <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://securehealth.dev\">securehealth.dev</a>",
      "backgroundColor": "#2ecc71",
      "textColor": "#ffffff",
      "isCloseable": true
    },
    "navbar": {
      "title": "SecureHealth Documentation",
      "logo": {
        "alt": "SecureHealth Logo",
        "src": "img/logo.png",
        "srcDark": "img/logo.png",
        "className": "navbar-logo",
        "width": "100px",
        "height": "100%"
      },
      "items": [
        {
          "type": "doc",
          "docId": "intro",
          "position": "left",
          "label": "Documentation"
        },
        {
          "href": "https://securehealth.dev",
          "label": "Live Demo",
          "position": "right"
        },
        {
          "href": "https://github.com/mrlynn/securehealth",
          "label": "GitHub",
          "position": "right"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "label": "Documentation",
          "href": "https://docs.securehealth.dev/"
        },
        {
          "label": "Features",
          "href": "https://docs.securehealth.dev/docs/concepts/hipaa-compliance"
        },
        {
          "label": "Security",
          "href": "https://docs.securehealth.dev/docs/concepts/security-architecture"
        },
        {
          "label": "Encryption Demo",
          "href": "https://securehealth.dev"
        },
        {
          "href": "https://github.com/mrlynn/securehealth",
          "label": "GitHub Repository"
        }
      ],
      "copyright": "© 2025 SecureHealth. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "powershell",
        "swift",
        "kotlin"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "mermaid": {
      "theme": {
        "light": "neutral",
        "dark": "forest"
      },
      "options": {}
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": true,
      "swcJsMinimizer": true,
      "swcHtmlMinimizer": true,
      "lightningCssMinimizer": true,
      "rspackBundler": true,
      "rspackPersistentCache": true,
      "ssgWorkerThreads": true,
      "mdxCrossCompilerCache": true
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": true
    },
    "experimental_router": "browser"
  },
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
